name 'loadbalance'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures loadbalance'
long_description 'Installs/Configures loadbalance'
version '2.0.0'
